name : CI Backend Pipeline

on : 
    push :
        branches : 
            - main
    pull_request : 
        branches :
            - main
    workflow_dispatch:
    
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        env:
          MONGODB_URL : ${{ secrets.MONGODB_URL }}
          JWT_SECRET : ${{ secrets.JWT_SECRET }}
          COOKIE_SECRET : ${{ secrets.COOKIE_SECRET }}
          REDIS_URL : ${{secrets.REDIS_URL}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name : Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run : npm install

            - name: Run test
              run : npm test


              